feat: add mentorsDetailList
kaiyuanshe/PWA pull request #20
Opened 2021-08-10 11:00 UTC by summer996

feat: add mentorsDetailList.

2021-08-17 09:26 UTC, summer996 commented
feat: add mentorsDetailList.

closes #12

2021-08-17 13:11 UTC, TechQuery requested changes

2021-08-17 13:11 UTC, TechQuery commented on src/page/userPage/index.tsx
> +                                            )}
自己手写一下**日期格式化**函数非常好，我之前封装过，直接引用会节省代码体积
https://web-cell.dev/web-utility/modules/date.html#formatDate

2021-08-17 13:11 UTC, TechQuery commented on src/page/userPage/index.tsx
> +                            {program.activityInfoList.map((item: Program) => {
直接在函数参数处解构，会让函数体代码更简洁。

2021-08-17 13:11 UTC, TechQuery commented on src/page/userPage/index.tsx
> +                                return (
箭头函数体没其它逻辑的话，可以省略 `return`，直接写成表达式。

2021-08-17 13:11 UTC, TechQuery commented on src/page/index.tsx
> +                        报名信息查看
此处应为“个人主页”

2021-08-17 13:47 UTC, TechQuery requested changes

2021-08-17 13:47 UTC, TechQuery commented on src/page/userPage/index.tsx
> +                                } = item;
我是说：参数处的 `item` 直接替换成解构

2021-08-18 08:22 UTC, TechQuery approved these changes

2021-08-18 08:23 UTC, merged